use terem; 
select * from terem.photos;

 insert into photos 
    (catalog_id, product_id, description, filename)
    values
(1, 1, 'Академик', 'akademik.jpeg'),
(1, 2, 'Акварель', 'akvarel.jpeg'),
(1, 3, 'Боярин', 'boyarin.jpeg'), 
(1, 4, 'Восход', 'voshod.jpeg'),
(1, 5, 'Генерал', 'general.jpeg'), 
(1, 6, 'Император', 'imperator.jpeg'), 
(1, 7, 'Канцлер', 'kancler.jpeg'), 
(1, 8, 'Маршал', 'marshal.jpeg'),
(1, 9, 'Маяковский', 'mayakovskiy.jpeg'), 
(1, 10, 'Полковник', 'polkovnik.jpeg'), 
(1, 11, 'Традиция', 'tradiciya.jpeg'),
(2, 12, 'Академик', 'akademik.jpeg'),
(2, 13, 'Акварель', 'akvarel.jpeg'),
(2, 14, 'Бордо', 'bordo,jpeg'), 
(2, 15, 'Боярин', 'boyarin.jpeg'),
(2, 16, 'Варяг', 'varyag.jpeg'),
(2, 17, 'Викинг', 'viking.jpeg'), 
(2, 18, 'Восход', 'voshod.jpeg'), 
(2, 19, 'Генерал', 'general.jpeg'),
(2, 20, 'Добрыня', 'dobrinya.jpeg'), 
(2, 21, 'Император', 'imperator.jpeg'),
(2, 22, 'Канцлер', 'kancler.jpeg'), 
(2, 23, 'Маршал', 'marshal.jpeg'), 
(2, 24, 'Маяковский', 'mayakovskiy.jpeg'), 
(2, 25, 'Песня', 'song.jpeg'), 
(2, 26, 'Полковник', 'polkovnik.jpeg'), 
(2, 27, 'Премьер', 'primer.jpeg'), 
(2, 28, 'Традиция', 'tradiciya.jpeg'), 
(3, 29, 'Академик', 'akademik.jpeg'), 
(3, 30, 'Акварель', 'akvarel.jpeg'), 
(3, 31, 'Бордо', 'bordo.jpeg'), 
(3, 32, 'Боярин', 'boyarin.jpeg'), 
(3, 33, 'Варяг', 'varyag.jpeg'), 
(3, 34, 'Викинг', 'viking.jpeg'), 
(3, 35, 'Генерал', 'general'), 
(3, 36, 'Добрыня', 'dobrinya.jpeg'), 
(3, 37, 'Император', 'imperator.jpeg'), 
(3, 38, 'Канцлер', 'kancler.jpeg'), 
(3, 39, 'Маршал', 'marshal.jpeg'), 
(3, 40, 'Маяковский', 'mayakovskiy.jpeg'), 
(3, 41, 'Песня', 'song.jpeg'), 
(3, 42, 'Полклвник', 'polkovnik.jpeg'), 
(3, 43, 'Премьер', 'primer.jpeg'), 
(4, 44, 'Богатырь', 'bogatir.jpej'), 
(4, 45, 'Богатырь ЛК', 'bogatir_lk.jpeg'),
(4, 46, 'Терем', 'terem.jpeg'), 
(4, 47, 'Терем ЛК', 'terem_lk.jpeg'), 
(5, 48, 'Охотник', 'ohotnik.jpeg'), 
(5, 49, 'Витязь', 'vityaz.jpeg'), 
(5, 50, 'Лидер ЛК', 'lider_lk.jpeg'), 
(5, 51, 'Лидер', 'lider.jpeg'), 
(5, 52,  'Малыш', 'malish.jpeg'), 
(6, 53, 'Баня', 'banya.jpeg'), 
(6, 54, 'Баня Лада', 'banya_lada.jpeg'), 
(6, 55, 'Баня СМ', 'banya_cm.jpeg'), 
(6, 56, 'Егерь', 'eger.jpeg'), 
(6, 57, 'Егерь СМ', 'eger_cm.jpeg'), 
(6, 58, 'Тайга', 'tayga.jpeg'), 
(6, 59, 'Тайга СМ', 'tayga_cm.jpeg'), 
(7, 60, 'Охотник', 'ohotnik.jpeg'),
(7, 61, 'Витязь', 'vityaz.jpeg'),  
(7, 62, 'Акварель', 'akvarel.jpeg'), 
(7, 63, 'Баня', 'banya.jpeg'), 
(7, 64, 'Барн', 'barn.jpeg'), 
(7, 65, 'Беседка', 'besedka.jpeg'), 
(7, 66, 'Беседка-барбекю','besedka_bar.jpeg'), 
(7, 67, 'Гараж', 'garag.jpeg'), 
(7, 68, 'Добрыня', 'dobrinya.jpeg'),
(7, 69, 'Егерь', 'eger.jpeg'),
(7, 70, 'Малыш', 'malish.jpeg'), 
(7, 71, 'Песня', 'song.jpeg'), 
(7, 72, 'Тайга', 'tayga.jpeg'), 
(8, 73, 'Гараж', 'garag.jpeg'), 
(9, 74, 'Беседка', 'besedka.jpeg'),
(9, 75, 'Беседка-барбекю', 'besedka_bar.jpeg');
